name: Render Jinja2 Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Jinja2
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name: Render the template using jinja2-action
        id: render_template
        uses: fletort/jinja2-template-action@v1
        with:
          keep_template: true
          data_file: './inventory/example-arm.yml'

      - name: Show rendered output
        run: cat ./examples-output/airgap/eib/output.yaml

      # Optional: Commit the rendered output file if needed
      - name: Commit rendered file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add rendered output"
          git push
